#ifndef COMMON_H
#define COMMON_H

#include <QString>
#include <QDateTime>

namespace DeploymentType {
	enum Value {
		XJ_CENTER,
		BJ_CENTER
	};
}

const QString XJ_CONFIGFILE_PATH = "../conf/xj-config.xml";
const QString BJ_CONFIGFILE_PATH = "../conf/bj-config.xml";
const QString DATE_FORMAT_STRING = "yyyy-MM-dd";
const QString TIME_FORMAT_STRING = "hh:mm:ss";
const QString DATETIME_FORMAT_STRING = "yyyy-MM-dd hh:mm:ss";

const qint32 MAX_RECEIVER_COUNT_PERSTATION = 2;

const qint32 TABLEWIDGET_HORIZONHEADER_HEIGHT = 25;

const qint32 RECEIVER_SHAREDBUFFER_ID = 1601;
const qint32 RECEIVER_SHAREDBUFFER_MAXITEMCOUNT = 200;
const qint32 RECEIVER_SHAREDBUFFER_MEMID_START_INDEX = 201;
const qint32 OTHERCENTER_SHAREDBUFFER_ID = 1602;
const qint32 OTHERCENTER_SHAREDBUFFER_MAXITEMCOUNT = 20;
const qint32 IGMAS_SHAREDBUFFER_ID = 1603;
const qint32 IGMAS_SHAREDBUFFER_MAXITEMCOUNT = 20;
const qint32 IGMAS_SHAREDBUFFER_MEMID_START_INDEX = 401;
const qint32 USER_REGISTER_INFO_SHAREDBUFFER_ID = 1501;
const qint32 USER_REGISTER_INFO_SHAREDBUFFER_MAXITEMCOUNT = 5000;
const qint32 USER_REALTIME_INFO_SHAREDBUFFER_ID = 101;
const qint32 USER_REALTIME_INFO_SHAREDBUFFER_MAXITEMCOUNT = 5000;

const qint32 RECEIVER_STATE_SHAREDBUFFER_ID = 102;
const qint32 RECEIVER_STATE_SHAREDBUFFER_MAXITEMCOUNT = 200;
const qint32 OTHERCENTER_STATE_SHAREDBUFFER_ID = 103;
const qint32 OTHERCENTER_STATE_SHAREDBUFFER_MAXITEMCOUNT = 20;
const qint32 IGMAS_STATE_SHAREDBUFFER_ID = 107;
const qint32 IGMAS_STATE_SHAREDBUFFER_MAXITEMCOUNT = 20;

const qint32 DLLSTATE_WRITE_TIMEINTERVAL = 1000;
const qint32 DLLSTATE_CHECK_TIMEINTERVAL = 1000;
const qint32 MESSAGE_CHECK_TIMEINTERVAL = 100;
const qint32 DEVICE_STATE_CHECK_TIMEINTERVAL = 1000;
const qint32 COMPONENT_COUNT = 6;
const qint32 DLL_COUNT = 24;
const qint32 COMPONENT_DLL_COUNT[COMPONENT_COUNT] = {3, 2, 6, 4, 5, 4};
const qint32 COMPONENT_STATEARRAY_INDEX[COMPONENT_COUNT] = {0, 3, 5, 11, 15, 20};
const QString COMPONENT_NAME[COMPONENT_COUNT] = {
    QString("MAINFRAMEWORK"), QString("RECEIVEANDBROADCAST"), QString("DATAPROCESSING"),
    QString("DATASTORING"), QString("USERMANAGER"), QString("SYSTEMMONITORANDMANAGER")};

#endif // COMMON_H

