#ifndef COMMON_H
#define COMMON_H

#include <QString>

namespace DeploymentType {
	enum Value {
        XJ_CENTER,
        BJ_CENTER
	};
}

const QString XJ_CONFIGFILE_PATH = "../conf/xj-config.xml";
const QString BJ_CONFIGFILE_PATH = "../conf/bj-config.xml";
const QString DATE_FORMAT_STRING = "yyyy-MM-dd";
const QString TIME_FORMAT_STRING = "hh:mm:ss";
const QString DATETIME_FORMAT_STRING = "yyyy-MM-dd hh:mm:ss";

const int MAX_RECEIVER_COUNT_PERSTATION = 2;

const int TABLEWIDGET_HORIZONHEADER_HEIGHT = 25;

const int RECEIVER_SHAREDBUFFER_ID = 1601;
const int RECEIVER_DATABUFFER_LENGTH = 4096 + 80;
const int RECEIVER_MAXITEMCOUNT = 200;
const int RECEIVER_MEMID_START_INDEX = 201;
const int BJCENTER_SHAREDBUFFER_ID = 1605;
const int IGMASSTATION_SHAREDBUFFER_ID = 1603;
const int IGMASSTATION_DATABUFFER_LENGTH = 4096 + 80;
const int IGMASSTATION_MAXITEMCOUNT = 200;
const int IGMASSTATION_MEMID_START_INDEX = 401;
const int IGMASDATACENTER_SHAREDBUFFER_ID = 1604;
const int IGMASDATACENTER_MAXITEMCOUNT = 20;
const int OTHERCENTER_SHAREDBUFFER_ID = 1602;
const int OTHERCENTER_MAXITEMCOUNT = 20;

const int USER_REGISTER_INFO_SHAREDBUFFER_ID = 1501;
const int USER_REGISTER_INFO_MAXITEMCOUNT = 5000;
const int USER_REALTIME_INFO_SHAREDBUFFER_ID = 101;
const int USER_REALTIME_INFO_MAXITEMCOUNT = 5000;

const int RECEIVER_STATE_SHAREDBUFFER_ID = 102;
const int OTHERCENTER_STATE_SHAREDBUFFER_ID = 103;
const int IGMAS_STATE_SHAREDBUFFER_ID = 107;

const int DLLSTATE_WRITE_TIMEINTERVAL = 1000;
const int DLLSTATE_CHECK_TIMEINTERVAL = 1000;
const int RESOURCE_CHECK_TIMEINTERVAL = 500;
const int MESSAGE_CHECK_TIMEINTERVAL = 10;
const int MESSAGE_MAX_COUNT = 100;
const int DEVICE_CONNECT_STATE_CHECK_TIMEINTERVAL = 100;
const int SHAREDBUFFER_WRITE_STATE_CHECK_TIMEINTERVAL = 100;
const int IGMASSTATION_DATA_RECEIVING_STATE_CHECK_TIMEINTERVAL = 1000;

const int COMPONENT_COUNT = 6;
const int DLL_COUNT = 24;
const int COMPONENT_DLL_COUNT[COMPONENT_COUNT] = {3, 2, 6, 4, 5, 4};
const int COMPONENT_STATEARRAY_INDEX[COMPONENT_COUNT] = {0, 3, 5, 11, 15, 20};
const QString COMPONENT_NAME[COMPONENT_COUNT] = {
    QString("MAINFRAMEWORK"), QString("RECEIVEANDBROADCAST"), QString("DATAPROCESSING"),
    QString("DATASTORING"), QString("USERMANAGER"), QString("SYSTEMMONITORANDMANAGER")};

#endif // COMMON_H

